### PR TITLE
Homework1_ZeyuHuang

### PR DESCRIPTION
**Pull request by Zeyuuuuuu**

### CODE REVIEW

**Comment by SWE-265P** [comment]
You didn't add your images to your homework. Also don't you the absolute path to the images, because then it will not be rendered on GitHub or anywhere else except your machine.

**Comment by SWE-265P** [comment]
Also please remove the gitignore file.

**Comment by Zeyuuuuuu** [comment]
> Also please remove the gitignore file.

Thank you for your comments. I've already uploaded the img to the Picture Bed and remove the gitignore file. Do I need to create a new branch for homework and use the other branch for Dairy only?

**Comment by SWE-265P** [comment]
In the future I would recommend splitting these commits up, but for now I will merge them and it is fine. 👍

**Pull request merged**
