### PR TITLE
merge commits

### PR DESCRIPTION
**Pull request by oscarli9**

### CODE REVIEW

**Comment by kajdreef** [comment]
These files already seem to be in the repository. 

image

Are you already resubmitting HW2?

**Comment by kajdreef** [comment]
@oscarli9 please take a look at my previous comment or this PR will be closed.

**Comment by oscarli9** [comment]
Hi Kaj,

Sorry for the late reply. Actually I didn't mean to resubmit hw2. When I
wanted to update my repo, Github showed that my repo was 4 commits ahead of
SWE265P/2020. I didn't know why I needed to recommit these old commits
while I already submitted my homework and they got merged into SWE265P/2020
a long time ago. However, I needed to make this pull request so that I
could normally update my repo, submit my diary and new homework. That's the
reason why I wrote "update my repo" instead of "resubmit hw2". The new
version of hw2 is about to be submitted by later today.

Best,
Oscar Li

**Comment by kajdreef** [comment]
Please don't make a pull request to this repository if it is not meant to submit homework, your diary, or any team contribution. If a PR was mad by accident then close it as soon as possible. I will close it now.

**Pull request closed without merging**
