### PR TITLE
Diary Update

### PR DESCRIPTION
**Pull request by Zeyuuuuuu**

### CODE REVIEW

**Comment by kajdreef** [comment]
There seems to be a merge conflict, please resolve this so it can be merged.

**Comment by Zeyuuuuuu** [comment]
I 

> @Zeyuuuuuu there seems to be a merge conflict, please resolve this so it can be merged.

I modified some of my previous diaries and now I don't know how to resolve the conflict. I've tried to delete the file and added it back, but it didn't work.

**Comment by Zeyuuuuuu** [comment]
I modify the file name by adding a space between my family name and given name. Is it possible to delete the "diaries/diary-ZeyuHuang.xlsx" file and stay with "diaries/diary-Zeyu Huang.xlsx"?

**Comment by kajdreef** [comment]
>I modify the file name by adding a space between my family name and given name. Is it possible to delete the "diaries/diary-ZeyuHuang.xlsx" file and stay with "diaries/diary-Zeyu Huang.xlsx"?

No, before you modify your diary you need to make sure you create a branch that is up to date with the upstream master. When you do that you will not run into merge conflicts.

**Comment by Zeyuuuuuu** [comment]
OK. I fix it. Thank you!

**Pull request merged**
